version: '3'
services:
  operatingsystem:
    image: redhat/ubi8:latest

  database:
    image: postgres:13
    restart: always
    env_file:
      ./sql/db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    restart: always

  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - nginx
      - database
      - operatingsystem