version: '3'
services:
  operatingsystem:
    image: redhat/ubi8:latest

  database:
    image: mysql:5.7
    restart: always

  nginx:
    image: nginx:latest
    restart: always

  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - nginx
      - database
      - operatingsystem