version: '3'
services:
  operatingsystem:
    image: redhat/ubi8:latest
    container_name: redhat8

  database:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: always
    
  heimdall-lite:
    image: mitre/heimdall-lite:latest
    container_name: heimdall-lite
    ports:
      - "3000:3000"
